_target_: mlops_project.model.DenseNetModel

in_channels: ${in_channels}
num_classes: ${num_classes}

spatial_dims: 2

pretrained: false

init_features: 64
growth_rate: 32
block_config: [6, 12, 24, 16]
dropout_prob: 0.0