wandb_version: 1

batch_size:
  value: 32
epochs:
  value: 10
model:
  value: densenet
optimizer.lr:
  value: 0.0001033388982321138
optimizer.name:
  value: AdamW
optimizer.weight_decay:
  value: 0.001
wandb.enabled:
  value: true
