program: src/mlops_project/train.py
name: hyperparameter-sweep-densenet
entity: brainy_mlops
project: densenet
method: bayes
metric:
  name: val/loss_epoch
  goal: minimize
command:
  - ${env}
  - PYTHONPATH=src
  - uv
  - run
  - python
  - ${program}
  - ${args_no_hyphens}
parameters:
  model:
    value: densenet
  batch_size:
    values: [16, 32, 64]
  epochs:
    value: 10
  optimizer.lr:
    min: 0.0001
    max: 0.01
    distribution: log_uniform_values
  optimizer.weight_decay:
    values: [0.001]
  optimizer.name:
    values: [AdamW]
  wandb.enabled:
    value: true
